#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────
# SimStudio — One-time setup
# Usage:  bash install.sh
# ─────────────────────────────────────────────────────────────────────────────

set -eu

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
LAUNCHER="$SCRIPT_DIR/Run SimStudio.command"

echo ""
echo "╔══════════════════════════════════════════╗"
echo "║   SimStudio — Optical Fiber Traffic Lab  ║"
echo "║            First-time setup              ║"
echo "╚══════════════════════════════════════════╝"
echo ""

# ── 1. Find Python 3.9+ ──────────────────────────────────────────────────────
echo "🔍  Locating Python 3.9+..."

PYTHON=""
for P in python3 /opt/homebrew/bin/python3 /usr/local/bin/python3 /usr/bin/python3; do
    if command -v "$P" &>/dev/null; then
        VER_OK=$("$P" -c "import sys; print('yes' if sys.version_info >= (3,9) else 'no')" 2>/dev/null || echo "no")
        if [ "$VER_OK" = "yes" ]; then
            PYTHON="$(command -v "$P")"
            break
        fi
    fi
done

if [ -z "$PYTHON" ]; then
    echo ""
    echo "❌  Python 3.9 or newer not found."
    echo "    Install it from https://www.python.org/downloads/ and run this script again."
    exit 1
fi

PY_VER=$("$PYTHON" -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
echo "✅  Python $PY_VER  →  $PYTHON"

# ── 2. Check tkinter ─────────────────────────────────────────────────────────
echo ""
echo "🔍  Checking tkinter..."

if ! "$PYTHON" -c "import tkinter" 2>/dev/null; then
    echo ""
    echo "❌  tkinter is not available in this Python installation."
    echo ""
    echo "    How to fix:"
    echo "      macOS  → Install the official Python from https://www.python.org/downloads/"
    echo "               (Homebrew Python intentionally excludes tkinter.)"
    echo "      Ubuntu → sudo apt install python3-tk"
    echo "      Fedora → sudo dnf install python3-tkinter"
    echo ""
    echo "    Then run this script again."
    exit 1
fi

echo "✅  tkinter OK."

# ── 3. Upgrade pip/setuptools/wheel ──────────────────────────────────────────
echo ""
echo "📦  Upgrading pip / setuptools / wheel..."

"$PYTHON" -m pip install --quiet --user --upgrade pip setuptools wheel || {
    echo "⚠️   pip upgrade failed (continuing — installed versions may still work)."
}

# ── 4. Install the project (editable) + all runtime dependencies ─────────────
echo ""
echo "📦  Installing SimStudio and dependencies..."
echo "    (numpy<2 is pinned to prevent the matplotlib ABI crash)"

# Install the project in editable mode; pyproject.toml declares all deps.
"$PYTHON" -m pip install --quiet --user -e "$SCRIPT_DIR" || {
    echo ""
    echo "❌  Dependency installation failed."
    echo "    Check the error above and re-run:  bash install.sh"
    exit 1
}

echo "✅  Dependencies installed."

# ── 5. Verify critical imports ───────────────────────────────────────────────
echo ""
echo "🔍  Verifying imports..."

VERIFY_FAILED=0

"$PYTHON" -c "import numpy, matplotlib, openpyxl, PIL; print('   numpy', numpy.__version__, '| matplotlib', matplotlib.__version__, '| openpyxl', openpyxl.__version__, '| Pillow OK')" || {
    echo "❌  One or more core imports failed (see above)."
    VERIFY_FAILED=1
}

"$PYTHON" -c "import docx; print('   python-docx OK (Word report enabled)')" 2>/dev/null || {
    echo "⚠️   python-docx not importable — Word report will be unavailable."
}

if [ "$VERIFY_FAILED" -eq 1 ]; then
    echo ""
    echo "❌  Import verification failed. Run the commands above manually to diagnose."
    exit 1
fi

echo "✅  All imports OK."

# ── 6. Generate local launcher ───────────────────────────────────────────────
echo ""
echo "🔧  Creating launcher..."

cat > "$LAUNCHER" <<LAUNCHER_EOF
#!/bin/bash
# SimStudio launcher — generated by install.sh
# macOS: double-click this file in Finder to start the simulator.
# Terminal: bash "Run SimStudio.command"

cd "\$(dirname "\$0")"
exec "$PYTHON" scripts/run_app.py
LAUNCHER_EOF

chmod +x "$LAUNCHER"
echo "✅  Launcher created:  Run SimStudio.command"

# ── Done ─────────────────────────────────────────────────────────────────────
echo ""
echo "══════════════════════════════════════════════════════════════"
echo "  Setup complete!"
echo ""
echo "  ▶  To launch SimStudio:"
echo "       • Double-click  \"Run SimStudio.command\"  in Finder"
echo "       • Or from this folder:  bash \"Run SimStudio.command\""
echo "══════════════════════════════════════════════════════════════"
echo ""
